name: Go CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
    
    - name: Install dependencies
      run: go get .
      
    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./... -json > TestResults.json
      
    - name: Update Test Results
      uses: actions/upload-artifact@v3
      with:
        name: Go-Test-results
        path: TestResults.json
        
    - name: Test Summary
      uses: test-summary/action@v2
      with:
        paths: "TestResults.json"
      if: always()
